### ISSUE TITLE
npm update

### ISSUE THREAD

**Issue by baversjo** [kwonoj/hunspell-dict-downloader#54]
Hello, the version on NPM doesn't work for me.
However, your git master has been working fine. 
Could you make a new release on NPM?

Thanks!

**Comment by kwonoj** [comment]
Most changes after latest release are just dependency version update - what doesn't work exactly?

**Comment by baversjo** [comment]
Only issue was that dependencies were outdated, npm didn't want to install my app.

**Comment by baversjo** [comment]
Actually you're right.
It was a security issue in one of your dependencies that prompted me to use your master where this dependency was updated to mitigate the security issue. Specifically, your package depended on `pacote` 6, which unless updated to 7 depended on a insecure version of `ssri` :
<img width="515" alt="screen shot 2018-05-04 at 19 00 01" src="https://user-images.githubusercontent.com/371678/39641142-7927167e-4fcd-11e8-9dd1-d6b0870fda1e.png">

**Comment by kwonoj** [comment]
sounds fair. publihsed 0.0.3.
