### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by thiagorova** [kwonoj/hunspell-dict-downloader#89]
Hi! first of all, thanks for this really cool package. I've been using it alongside electron-hunspell!

So, I just tested this on a Windows 10 system (using an electron program built with electron-winstaller), and I had an error when I tried to install a package (I tested with 'pt-br', if you need, I can test with others). The Error I got was:

> Dictionary is installed, but failed to check integrity
> at Object.<anonymous> (C:\ ... \createDownloader.js:79)

Looking at your code, at the method install, it seems that:
`  const isValid = await isInstalledDictionaryValid(dictionaryDirectory, langRegionCode);`
is returning false.

As you can see from the code below (I adapted it a little to put here, but the idea is pretty much this), I first check to see if the language pack is installed, and if it isn't I try to install it before doing anything else.

```
dictDownloader.createDownloader(dictPath).then(manager => {
    let lang = 'pt-br'
    if (!manager.installedDictionaries.includes(lang)) { 
      // returns false, aka language package not installed
      return manager.installDictionary(langSet)
  }
}).then(() => {
  // use the language package installed for spell checking
}).catch(err => {
      console.log(err)
    })
```

I'm not sure if I'm doing something stupid, if there is a Windows dependency that I'm supposed to install or whether this is an actual bug. On a MacOs, at least, it worked perfectly (both installed versions and in development).
Any ideas?
Thanks again

**Comment by kwonoj** [comment]
What does log says if you enable log via `enableLogger`? it'll try to tell the reason why validation fails. 
(https://github.com/kwonoj/hunspell-dict-downloader/blob/master/src/isInstalledDictionaryValid.ts#L29-L42) it could be either hash mismatch or fail to access files for some reason.

There is no platform specific dependencies at least as far as I can tell.

**Comment by thiagorova** [comment]
Sorry for the stupid question. 
> What does log says if you enable log via `enableLogger?`

how do I do this? I did not find anything related to enableLogger neither in this package nor in electron docs...

**Comment by kwonoj** [comment]
https://github.com/kwonoj/hunspell-dict-downloader/blob/master/src/index.ts#L4

**Comment by kwonoj** [comment]
I'm afraid this is happening inside of `pacote` (which is module used in npm itself to install deps) and failing install for similar reason as other npm deps install fails on windows. I'd suggest to try out with bare pacote directly and see if there's same errors, and trying to analyze why path resolution fails inside of those module.

**Comment by kwonoj** [comment]
This is upstream issues and unfortunately I can't fix via my codes in this modules. I may bump up pacote later some times if it fixes but do not have strong ETA.

**Comment by kwonoj** [comment]
https://github.com/kwonoj/hunspell-dict-downloader/releases/tag/v1.0.0 for latest pacote.

**Comment by thiagorova** [comment]
ok, thanks a lot for your help! If I find anything new, I'll send you a message here. maybe it'll help others!

**Comment by thiagorova** [comment]
so, as I expected, the problem stopped happening when I set a folder outside of the .asar package, since that makes me independent of `pacote`. Not quite a perfect solution, but it worked well in my case as I already had a user selected folder.
